[package]
name = "AptosTripOMGTEST"
version = "1.0.0"

[addresses]
deploy_addr = "0xb7dfd36fb874559f774ffb04b2ad84acadf1c410e9a155266fc9096d375667fc"
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
aptos_token_objects = "0x4"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-token-objects" }

[dev-dependencies]